# Generated by Django 5.0.2 on 2024-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='images/user_images/profile_image.jpg', null=True, upload_to='images/user_images/'),
        ),
    ]
