# Generated by Django 5.0.2 on 2024-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Info',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_image', models.ImageField(upload_to='')),
                ('plant_common_name', models.CharField(max_length=50)),
                ('plant_scientific_name', models.CharField(max_length=50)),
                ('is_affected', models.BooleanField(default=False)),
                ('disease_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('cause', models.CharField(max_length=50)),
                ('solution', models.CharField(max_length=50)),
            ],
        ),
    ]
