# Generated by Django 5.0.2 on 2024-04-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_info',
            old_name='plant_common_name',
            new_name='plant_name',
        ),
        migrations.RemoveField(
            model_name='plant_info',
            name='plant_scientific_name',
        ),
    ]
