# Generated by Django 5.0.2 on 2024-04-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_info',
            old_name='product_description',
            new_name='plant_description',
        ),
    ]
