# Generated by Django 5.0.2 on 2024-04-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_plant_common_name_plant_info_plant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_info',
            name='disease_name',
        ),
    ]
