# Generated by Django 5.0.2 on 2024-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_plant_info_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_info',
            name='cause',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='solution',
            field=models.TextField(max_length=50),
        ),
    ]
