# Generated by Django 5.0.2 on 2024-04-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_plant_info_cause_alter_plant_info_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_info',
            name='cause',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plant_info',
            name='solution',
            field=models.TextField(max_length=500),
        ),
    ]
